import type { AgenticBotSchema, ConversationState, UploadedDocument } from '@/types/agentic';
import { generateAgentPrompt, shouldUseAutoGeneration } from '@/lib/generate-agent-prompt';

interface BusinessProfile {
  business_name?: string;
  business_type?: string;
  business_description?: string;
  products_services?: string;
  target_audience?: string;
  unique_selling_points?: string;
  location?: string;
}

/**
 * Builds the complete system prompt for the agent
 * Minimalist mission-based prompt optimized for GPT-5 Nano
 */
export function buildSystemPrompt(
  effectiveBusinessName: string,
  botSchema: AgenticBotSchema,
  businessProfile: BusinessProfile | null,
  currentState: ConversationState,
  uploadedDocuments: UploadedDocument[],
  allRequiredKeys: string[],
  missingInfo: string[],
  imageAnalysis?: string,
  messages?: Array<{ role: string; content: string }>
): string {
  // Build business context if available
  const useAutoPrompt = shouldUseAutoGeneration(botSchema);
  let businessContext = '';
  
  if (useAutoPrompt && businessProfile) {
    console.log('✅ USING AUTO-GENERATED PROMPT');
    businessContext = generateAgentPrompt(
      {
        business_name: effectiveBusinessName,
        business_type: businessProfile.business_type,
        business_description: businessProfile.business_description,
        products_services: businessProfile.products_services,
        target_audience: businessProfile.target_audience,
        unique_selling_points: businessProfile.unique_selling_points,
        location: businessProfile.location,
      },
      botSchema,
      effectiveBusinessName,
      botSchema.system_prompt || ''
    );
  } else {
    businessContext = botSchema.system_prompt || '';
  }

  // Format required fields for clarity
  const requiredFieldsList = Object.entries(botSchema.required_info).map(([key, info]) => 
    `- ${key}: ${info.description}${info.example ? ` (e.g., ${info.example})` : ''}`
  ).join('\n');

  // State information
  const gatheredInfoList = Object.keys(currentState.gathered_information).length > 0 
    ? Object.entries(currentState.gathered_information).map(([key, value]) => `${key}: "${value}"`).join('\n')
    : 'None yet';
  
  const missingInfoList = missingInfo.length > 0 
    ? missingInfo.map(key => `${key}: ${botSchema.required_info[key].description}`).join('\n')
    : 'All information collected!';

  // Image context
  const imageSection = imageAnalysis ? `

IMAGE ANALYSIS (from user's uploaded image):
${imageAnalysis}

` : '';

  // Document context
  const documentSection = uploadedDocuments.length > 0 ? `

UPLOADED DOCUMENTS:
${uploadedDocuments.map((doc, i) => `
Document ${i + 1}: ${doc.filename}
${doc.extracted_text}
`).join('\n')}

` : '';

  // Build minimalist prompt
  const agentSystemPrompt = `${businessContext}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

IDENTITY:
You are the Senior Intake Specialist for ${effectiveBusinessName}. Your job is to have a natural, text-based conversation to screen leads.

THE MISSION:
Your goal is to understand the user's needs and collect these required fields:
${requiredFieldsList}

Do NOT turn this into an interrogation. Collect them naturally as the conversation flows.

THE UNIVERSAL GUIDELINE:
Be a Consultative Expert. If the user states a problem, diagnose it briefly to build trust before asking for contact info. Match their vibe (casual/SMS style).

${imageSection}${documentSection}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STATE MANAGEMENT:

Here is what you know:
${gatheredInfoList}

Here is what is missing:
${missingInfoList}

Do not ask for what you already have.

CONFIRMATION:
When all fields are collected, present a summary. If the user agrees (in any way), set phase to 'completed'. You do not need a specific signature phrase.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

OUTPUT FORMAT (return VALID JSON):
{
  "reply": "Your natural, conversational response to the user",
  "extracted_information": {
    "info_key": "value you learned from their message"
  },
  "updated_phase": "introduction|collecting|answering_questions|confirmation|completed",
  "current_topic": "The information key you're currently discussing (or null)",
  "reasoning": "Brief explanation of your decision (for debugging)"
}

The reply content should be fully generated by your reasoning - be natural and conversational.`;

  return agentSystemPrompt;
}

